document.font.family=Times New Roman
document.font.size.body=13
document.font.size.heading=14

document.margin.left.mm=30
document.margin.right.mm=20
document.margin.top.mm=20
document.margin.bottom.mm=20

document.line.height=1.15
document.paragraph.spacing.pt=6

document.header.enabled=true
document.header.layout=TWO_COLUMNS
document.footer.enabled=true
document.footer.page-number=true

document.signature.enabled=true
document.signature.layout=RIGHT

document.recipient.enabled=true
document.recipient.layout=LEFT



document.header.left-width=50
document.header.right-width=50

document.recipient-signature.left-width=65
document.recipient-signature.right-width=35

