

document.header-left-pattern=^(TỈNH ỦY|CÔNG TY|ĐẢNG ỦY).*
document.header-right-pattern=^ĐẢNG CỘNG SẢN VIỆT NAM$

document.header-date-left-pattern=^Số:.*
document.header-date-right-pattern=.*ngày.*tháng.*năm.*

document.recipient-pattern=^Nơi nhận:$
document.signature-pattern=^T/M .*

document.section-pattern=^[IVX]+\..*
document.sub-section-pattern=^[0-9]+\..*

document.title-pattern=^NGHỊ QUYẾT$
document.title-sub-pattern=^(ĐẠI HỘI|LẦN THỨ).*

document.heading-pattern=^(QUYẾT NGHỊ|KẾT LUẬN|CHỈ THỊ)$